swagger: '2.0'
info:
  title: Teachers Blog API
  version: 1.0.0
  description: |
    Блог преподавателей факультета с REST API на Flask
    ### Особенности:
    - JWT-авторизация
    - Ролевая модель (admin / teacher / student)
host: 127.0.0.1:5000
basePath: /api
schemes:
  - http

securityDefinitions:
  BearerAuth:
    type: apiKey
    name: Authorization
    in: header
    description: Введите "Bearer <токен>"

security:
  - BearerAuth: []

tags:
  - name: Аутентификация и пользователи
    description: Эндпоинты для работы с пользователями и авторизацией
  - name: Статьи
    description: Управление блогами и статьями
definitions:
  User:
    type: object
    properties:
      id:
        type: integer
        example: 1
      username:
        type: string
        example: "ivanov"
      email:
        type: string
        example: "ivanov@example.com"
      role:
        type: string
        enum: ["teacher", "student", "admin"]
        example: "student"
      is_active:
        type: boolean
        example: true
      created_at:
        type: string
        format: date-time
        example: "2023-01-01T12:00:00Z"

  Post:
    type: object
    properties:
      id:
        type: integer
        example: 1
      title:
        type: string
        example: "Мой первый пост"
      content:
        type: string
        example: "Текст поста..."
      author_id:
        type: integer
        example: 1
      created_at:
        type: string
        format: date-time
        example: "2023-01-01T12:00:00Z"
      updated_at:
        type: string
        format: date-time
        example: "2023-01-02T15:00:00Z"

  Comment:
    type: object
    properties:
      id:
        type: integer
        example: 1
      content:
        type: string
        example: "Комментарий к посту"
      post_id:
        type: integer
        example: 1
      author_id:
        type: integer
        example: 2
      created_at:
        type: string
        format: date-time
        example: "2023-01-01T14:00:00Z"

  Reaction:
    type: object
    properties:
      id:
        type: integer
        example: 1
      emoji:
        type: string
        example: "👍"
      post_id:
        type: integer
        example: 1
      user_id:
        type: integer
        example: 2

  AuthRequest:
    type: object
    required:
      - email
      - password
    properties:
      email:
        type: string
        example: "admin@example.com"
      password:
        type: string
        example: "admin123"

  AuthResponse:
    type: object
    properties:
      access_token:
        type: string
        example: "eyJhbGciOi..."

  RegisterRequest:
    type: object
    required:
      - username
      - email
      - password
      - role
    properties:
      username:
        type: string
        example: "student1"
      email:
        type: string
        example: "student1@example.com"
      password:
        type: string
        example: "password123"
      role:
        type: string
        enum: ["teacher", "student"]
        example: "student"

  ErrorResponse:
    type: object
    properties:
      msg:
        type: string
        example: "Ошибка авторизации"